<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Data.EFCore.Sqlite\Kwy.Data.EFCore.Sqlite.csproj" />
    <ProjectReference Include="..\Kwy.MVVM.WPF\Kwy.MVVM.WPF.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF\Kwy.UI.WPF.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF.Components\Kwy.UI.WPF.Components.csproj" />
    <ProjectReference Include="..\KwyTemplate.Contracts\KwyTemplate.Contracts.csproj" />
  </ItemGroup>

</Project>
