<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Device.PLC.Hsl\Kwy.Device.PLC.Hsl.csproj" />
    <ProjectReference Include="..\Kwy.MVVM\Kwy.MVVM.csproj" />
    <ProjectReference Include="..\Kwy.ComponentModel\Kwy.ComponentModel.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Visa\Kwy.Communicate.Visa.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.TcpSerial\Kwy.Communicate.TcpSerial.csproj" />
    <ProjectReference Include="..\Kwy.Device.Abstractions\Kwy.Device.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Device.Core\Kwy.Device.Core.csproj" />
    <ProjectReference Include="..\Kwy.Device.PLC.Abstractions\Kwy.Device.PLC.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Device.PLC.Core\Kwy.Device.PLC.Core.csproj" />
    <ProjectReference Include="..\Kwy.Device.Instruments\Kwy.Device.Instruments.csproj" />
    <ProjectReference Include="..\Kwy.Device.IoCard.Advantech\Kwy.Device.IoCard.Advantech.csproj" />
    <ProjectReference Include="..\Kwy.Files\Kwy.Files.csproj" />
    <ProjectReference Include="..\KwyTemplate.Contracts\KwyTemplate.Contracts.csproj" />
  </ItemGroup>

</Project>
