<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KwyPecvd.Contracts.Grpc\KwyPecvd.Contracts.Grpc.csproj" />
    <ProjectReference Include="..\KwyPecvd.Device\KwyPecvd.Device.csproj" />
    <ProjectReference Include="..\KwyPecvd.Process\KwyPecvd.Process.csproj" />
  </ItemGroup>

</Project>
