<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Communicate.Abstractions\Kwy.Communicate.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Core\Kwy.Communicate.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NationalInstruments.Common">
      <HintPath>DLL\NationalInstruments.Common.dll</HintPath>
    </Reference>
    <Reference Include="NationalInstruments.NI4882">
      <HintPath>DLL\NationalInstruments.NI4882.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
