<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Device.Abstractions\Kwy.Device.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.MVVM\Kwy.MVVM.csproj" />
    <ProjectReference Include="..\KwyTemplate.Contracts\KwyTemplate.Contracts.csproj" />
    <ProjectReference Include="..\KwyTemplate.Device\KwyTemplate.Device.csproj" />
  </ItemGroup>

</Project>
