<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\eng\Kwy.Device.Core.Version.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kwy.Communicate.Abstractions\Kwy.Communicate.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Device.Abstractions\Kwy.Device.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Device.Core\Kwy.Device.Core.csproj" />
    <ProjectReference Include="..\Kwy.Device.Instruments.Abstractions\Kwy.Device.Instrument.Abstractions.csproj" />
  </ItemGroup>
</Project>
