<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Logging.Serilog\Kwy.Logging.Serilog.csproj" />
    <ProjectReference Include="..\Kwy.MVVM.WPF\Kwy.MVVM.WPF.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF\Kwy.UI.WPF.csproj" />
    <ProjectReference Include="..\KwyPecvd.App\KwyPecvd.App.csproj" />
  </ItemGroup>

</Project>
