<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AakStudio.Shell.UI.Themes.AvalonDock" Version="4.72.0" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.ComponentModel\Kwy.ComponentModel.csproj" />
    <ProjectReference Include="..\Kwy.Files\Kwy.Files.csproj" />
    <ProjectReference Include="..\Kwy.MVVM.WPF\Kwy.MVVM.WPF.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF\Kwy.UI.WPF.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF.Components\Kwy.UI.WPF.Components.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF.FlowDesigner\Kwy.UI.WPF.FlowDesigner.csproj" />
    <ProjectReference Include="..\Kwy.Vision.Abstractions\Kwy.Vision.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Vision.WPF\Kwy.Vision.WPF.csproj" />
    <ProjectReference Include="..\KwyTemplate.Contracts\KwyTemplate.Contracts.csproj" />
  </ItemGroup>

</Project>
