<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Secs4Net" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Communicate.Core\Kwy.Communicate.Core.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Secs\Kwy.Communicate.Secs.csproj" />
  </ItemGroup>

</Project>
