<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.MVVM.WPF\Kwy.MVVM.WPF.csproj" />
    <ProjectReference Include="..\Kwy.UI.WPF\Kwy.UI.WPF.csproj" />
    <ProjectReference Include="..\KwyPecvd.Contracts.App\KwyPecvd.Contracts.App.csproj" />
  </ItemGroup>

</Project>
