<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Kwy.Communicate.FMdb</PackageId>
    <Version>1.0.0</Version>
    <Product>Kwy Communicate</Product>
    <Description>FluentModbus 5.3.2 client wrapper for Modbus TCP and Modbus RTU.</Description>
    <PackageTags>Kwy;Communication;Modbus;FluentModbus;ModbusTcp;ModbusRtu</PackageTags>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentModbus" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Communicate.Abstractions\Kwy.Communicate.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Core\Kwy.Communicate.Core.csproj" />
  </ItemGroup>


</Project>

