<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\eng\Kwy.Device.Core.Version.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Communicate.Abstractions\Kwy.Communicate.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Core\Kwy.Core.csproj" />
  </ItemGroup>

</Project>
