<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kwy.Communicate.Abstractions\Kwy.Communicate.Abstractions.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Core\Kwy.Communicate.Core.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.FMdb\Kwy.Communicate.FMdb.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Gem\Kwy.Communicate.Gem.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Gem300\Kwy.Communicate.Gem300.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Mqtt\Kwy.Communicate.Mqtt.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.OpcUa\Kwy.Communicate.OpcUa.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.TcpSerial\Kwy.Communicate.TcpSerial.csproj" />
    <ProjectReference Include="..\Kwy.Communicate.Visa\Kwy.Communicate.Visa.csproj" />
  </ItemGroup>
</Project>
